[project]
name = "mouse-thingy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.7",
    "pyautogui>=0.9.54",
    "pynput>=1.7.6",
]
